name: Create EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vault CLI
        run: |
          wget -q https://releases.hashicorp.com/vault/1.20.3/vault_1.20.3_linux_amd64.zip
          unzip -o vault_1.20.3_linux_amd64.zip
          sudo mv vault /usr/local/bin/
          vault version

      - name: Login to Vault
        run: |
          TOKEN=$(vault write -field=token auth/approle/login \
            role_id="${{ secrets.VAULT_ROLE_ID }}" \
            secret_id="${{ secrets.VAULT_SECRET_ID }}")

          echo "VAULT_TOKEN=$TOKEN" >> $GITHUB_ENV
          echo "Successfully logged into Vault"

      - name: Read AWS credentials
        run: |
          export VAULT_TOKEN="${{ env.VAULT_TOKEN }}"

          vault kv get secret/aws

          AWS_KEY=$(vault kv get -field=AWS_ACCESS_KEY_ID secret/aws)
          AWS_SECRET=$(vault kv get -field=AWS_SECRET_ACCESS_KEY secret/aws)

          echo "::add-mask::$AWS_KEY"
          echo "::add-mask::$AWS_SECRET"

          echo "AWS_ACCESS_KEY_ID=$AWS_KEY" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
